In [1]:
import numpy as np

In [2]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
type(data)

numpy.ndarray

In [5]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
data.ndim

2

In [7]:
data.shape

(3, 2)

In [8]:
data.size

6

In [9]:
data.dtype

dtype('int64')

In [10]:
data.nbytes

48

In [11]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [12]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [13]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
data = np.array([1, 2, 3], dtype=np.float)

In [15]:
data.dtype

dtype('float64')

In [16]:
data

array([1., 2., 3.])

In [17]:
data = np.array(data, dtype=np.int)

In [18]:
data

array([1, 2, 3])

In [19]:
data.dtype

dtype('int64')

In [20]:
data.astype(np.float)

array([1., 2., 3.])

In [21]:
d1 = np.array([1, 2, 3], dtype=np.float)

In [22]:
d2 = np.array([1, 2, 3], dtype=np.complex)

In [23]:
d1.dtype, d2.dtype

(dtype('float64'), dtype('complex128'))

In [24]:
d1+d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1+d2).dtype

dtype('complex128')

In [28]:
np.sqrt(np.array([1, 0, -1]))

<ipython-input-28-cdd674f2c768>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([1, 0, -1]))


array([ 1.,  0., nan])

In [29]:
np.sqrt(np.array([1, 0, -1], dtype=np.complex))

array([1.+0.j, 0.+0.j, 0.+1.j])

In [30]:
data = np.array([1, 2, 3], dtype=np.complex)

In [31]:
data.real

array([1., 2., 3.])

In [32]:
data.imag

array([0., 0., 0.])

In [33]:
data.imag.dtype

dtype('float64')

In [34]:
data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [35]:
data.ndim

1

In [36]:
data.shape

(4,)

In [37]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [38]:
data.ndim

2

In [39]:
data.shape

(2, 2)

In [40]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((1, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [44]:
np.full(10, 5.4)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [45]:
x1 = np.empty(5)
x1

array([4.68224053e-310, 0.00000000e+000, 0.00000000e+000, 2.22809558e-312,
       5.38531554e-322])

In [46]:
x1.fill(3.2)

In [47]:
x1

array([3.2, 3.2, 3.2, 3.2, 3.2])

In [48]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [50]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
np.logspace(0, 10, 5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [52]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [53]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

In [54]:
np.meshgrid(x, y)

[array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]])]

In [55]:
X, Y = np.meshgrid(x, y)

In [56]:
Z = (X+Y)**2

In [57]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [58]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [59]:
np.ones_like(x)

array([[1, 1],
       [1, 1]])

In [60]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [62]:
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [63]:
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [64]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [65]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
a[0], a[-1], a[4]

(0, 10, 4)

In [67]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[100:-200]

array([], dtype=int64)

In [69]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [70]:
a[:5]

array([0, 1, 2, 3, 4])

In [71]:
a[:-5]

array([0, 1, 2, 3, 4, 5])

In [72]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [73]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [74]:
f = lambda m, n: n+10*m

In [77]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [78]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [79]:
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [81]:
A[1:, ]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [82]:
A[1, :]

array([10, 11, 12, 13, 14, 15])

In [83]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [84]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [85]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [86]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [87]:
B = A[1:5, 1:5]

In [88]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [89]:
B[:, :] = 0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [90]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [91]:
C[:, :] = 1
C

array([[1, 1],
       [1, 1]])

In [92]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [94]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [95]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [96]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [97]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [98]:
A = np.arange(10)

In [99]:
indices = [2, 4, 6]
B = A[indices]

In [100]:
B[0] = -1
B, A

(array([-1,  4,  6]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [101]:
A[indices] = -1
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [102]:
A = np.arange(10)
A[A > 5] = -1
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [103]:
data = np.array([[1, 2], [3, 4]])

In [104]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [105]:
data.reshape((1, 4))

array([[1, 2, 3, 4]])

In [106]:
data = np.array([[1, 2], [3, 4]])

In [107]:
data.ravel()

array([1, 2, 3, 4])

In [108]:
data

array([[1, 2],
       [3, 4]])

In [109]:
data.flatten()

array([1, 2, 3, 4])

In [110]:
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [111]:
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [112]:
column.shape

(5, 1)

In [113]:
data.shape

(5,)

In [114]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [115]:
row.shape

(1, 5)

In [116]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [118]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [119]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [120]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [121]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [122]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [123]:
x+y

array([[ 6,  8],
       [10, 12]])

In [124]:
y-x

array([[4, 4],
       [4, 4]])

In [125]:
x*y

array([[ 5, 12],
       [21, 32]])

In [126]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [127]:
x*2

array([[2, 4],
       [6, 8]])

In [128]:
2**x

array([[ 2,  4],
       [ 8, 16]])

In [129]:
y/2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [130]:
(y/2).dtype

dtype('float64')

In [131]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
z = np.array([1, 2, 3, 4])

In [132]:
x/z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [133]:
z = np.array([[2, 4]])
z

array([[2, 4]])

In [134]:
z.shape

(1, 2)

In [135]:
x/z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [136]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [138]:
y = np.sin(np.pi*x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [139]:
def heaviside(x):
    return 1 if x > 0 else 0
heaviside(3.4)

1

In [140]:
heaviside(0), heaviside(-2.3)

(0, 0)

In [141]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [142]:
heaviside = np.vectorize(heaviside)

In [143]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [145]:
data = np.random.normal(size=(15, 15))
data

array([[-9.74983593e-01,  1.04892365e+00,  9.93956379e-03,
         2.96503169e-01,  5.12238835e-01,  1.19712405e+00,
        -1.45410590e+00,  1.20792712e+00,  1.06879497e+00,
        -8.35685005e-01, -1.65210955e-01,  6.89706293e-01,
        -2.90344025e+00, -2.65341213e-02,  2.68941655e-01],
       [-7.36959928e-01, -1.31640681e+00, -9.72465409e-01,
         1.04424525e+00, -1.87119089e+00,  3.60420173e-01,
        -5.16890015e-02,  3.25007734e-01,  6.82649989e-01,
         7.56927466e-01, -1.11057414e+00,  1.05759668e+00,
        -1.77983670e+00,  9.63513471e-01,  3.62714532e-02],
       [ 2.55118600e-01, -1.40544958e+00, -4.47423689e-01,
        -2.75610551e+00,  6.45303543e-01, -1.04261412e+00,
        -3.24443622e-01,  8.57555260e-01, -1.49525752e+00,
        -1.31475422e+00, -8.81629520e-01, -2.62400331e-01,
        -1.28204724e+00,  2.73908849e+00,  1.38449778e+00],
       [ 4.88363252e-01,  6.91040270e-01, -9.43799976e-02,
         4.14489508e-01,  9.57696356e-01,  1.20619364

In [146]:
 np.mean(data)

0.027570447399590605

In [147]:
data.mean()

0.027570447399590605

In [148]:
data = np.random.normal(size=(5, 10, 15))

In [149]:
data.sum(axis=0).shape

(10, 15)

In [150]:
data.sum(axis=(0, 2)).shape

(10,)

In [151]:
data.sum()

-49.48178747274723

In [152]:
data.sum(axis=(0, 2))

array([ -4.60430153, -22.01392094,   1.33127169,   6.4728578 ,
        -8.59256006,  -5.30499554, -14.53236781,  -6.20928805,
         4.37696868,  -0.40545173])

In [153]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [154]:
a < b

array([ True,  True, False, False])

In [155]:
np.all(a < b)

False

In [156]:
np.any(a < b)

True

In [157]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [158]:
x = np.linspace(-5, 5, 11)
pulse(x, -2, 1, 5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [159]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
x[[1, 1]]

array([1, 1])

In [161]:
a = np.unique([1, 2, 3, 3])
a

array([1, 2, 3])

In [162]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])
b

array([2, 3, 4, 5, 6])

In [163]:
np.in1d(a, b)

array([False,  True,  True])

In [164]:
np.all(np.in1d(a, b))

False

In [165]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [166]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [167]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

(1, 2, 3, 4, 5)

In [168]:
data.T.shape

(5, 4, 3, 2, 1)

In [169]:
x = np.random.rand(10)
x

array([0.80959308, 0.66632122, 0.68176989, 0.07926961, 0.00511725,
       0.6323612 , 0.73934221, 0.36889843, 0.90596211, 0.86599264])

In [170]:
np.sort(x)

array([0.00511725, 0.07926961, 0.36889843, 0.6323612 , 0.66632122,
       0.68176989, 0.73934221, 0.80959308, 0.86599264, 0.90596211])

In [171]:
x

array([0.80959308, 0.66632122, 0.68176989, 0.07926961, 0.00511725,
       0.6323612 , 0.73934221, 0.36889843, 0.90596211, 0.86599264])

In [172]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [175]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [176]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [177]:
x = np.arange(3)
x

array([0, 1, 2])

In [178]:
np.dot(A, x)

array([ 5, 14, 23])

In [179]:
A.dot(x)

array([ 5, 14, 23])

In [180]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [181]:
A = np.matrix(A)
B = np.matrix(B)

In [182]:
Ap = B * A * B.I

In [183]:
Ap

matrix([[ 0.30908861,  1.07205208, -0.16087482],
        [ 0.03489748,  1.16215171, -0.22225908],
        [ 0.81230608, -0.12636342, -0.18469953]])

In [184]:
np.dot(B, np.dot(A, np.linalg.inv(B)))

matrix([[ 0.30908861,  1.07205208, -0.16087482],
        [ 0.03489748,  1.16215171, -0.22225908],
        [ 0.81230608, -0.12636342, -0.18469953]])

In [185]:
np.inner(x, x)

5

In [186]:
np.dot(x, x)

5

In [187]:
y = x[:, np.newaxis]

In [188]:
y

array([[0],
       [1],
       [2]])

In [189]:
np.dot(y.T, y)

array([[5]])

In [190]:
x = np.array([1, 2, 3])

In [191]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])